### ISSUE TITLE
Memory improvement in lsort

### ISSUE THREAD

**Issue by apregier** [hall-lab/svtools#10]
Current sorting approach won't scale - need to limit the amount stored in memory, perhaps by chromosome and variant type.

**Comment by apregier** [comment]
Another possible approach - similar to unix sort, you could write out temp sorted partitions.

**Comment by ernfrid** [comment]
This addressed by https://github.com/hall-lab/svtools/pull/17 which implements an external merge sort.

Memory usage for a 1000 person, 800,000 line cohort is now ~6GB and merging completes in ~30 minutes of wall clock. In testing on a 5000 person cohort, ~5000 lines per file, merging completes in ~3:40h with ~5G of RAM.
