### ISSUE TITLE
VCF output of speedseq(lumpy) SVtype BND are translocations?

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/svtools#104]
Hi there,

Lumpy output vcf files with 4 different SV types: `BND`, `DEL`, `INV` and `DUP`, Something I have asked [here](https://github.com/hall-lab/svtools/issues/5)

For BNDs:
I understand that if both break ends are in different chromosomes, this is more likely to be a translocation, but how about break ends on the same chromosome? I want to make sure that BNDs are always translocations or sometimes it is just SV types can not be determined and represented in the break end format.

I read [here](https://gist.github.com/ernfrid/e6af5c7a56758aaf3fbb#vcf-entry-as-bnd-entries-again-precise) and saw DEL can be represented in BND format, but the example is showing break points on two different chromosomes, so it is a bit confusing.

Thanks for answering me.

Best,
Ming

**Comment by ernfrid** [comment]
In that example of a simple deletion the chromosome name is `chr` and the numbers are positions. Perhaps not the best choice, but it is intended to show BND entries on the same chromosome. Sorry for the confusion.

In terms of Lumpy output, I am not as confident as to the correct answer. I do think you are correct that if both breakends are on the same chromosome then the interpretation is that Lumpy was unable to determine that it belonged to any of the other classes (`DEL`, `INV`, `DUP` see https://github.com/arq5x/lumpy-sv/blob/7d60167d17347ceadb297e9a66c36df8013d1b83/src/lumpy/SV_VcfVariant.cpp#L110-L135). I would defer to @ryanlayer or @cc2qe on that though as I'm just guess from the source.

**Comment by cc2qe** [comment]
BND is a catch-all for a generic breakpoint, so you can't assume all to be translocations

When LUMPY reports a BND with both sides on the same chromsome, it is indicating misoriented reads (++ or --). When we see reciprocal evidence (**both** ++ and -- from the same event), LUMPY calls this an inversion. Howevere, when only one of these orientations are observed, it is designated a BND. Some of these "one-sided inversion" BNDs might be true inversions where we miss one of the sides, and others may be parts of complex variants or artifacts.

**Comment by crazyhottommy** [comment]
Thanks for clarifying this. So, a BND with both sides on the same chromosome can be an `INV`. Can it be a `DUP` or `DEL`?

**Comment by cc2qe** [comment]
LUMPY never represents breakpoints with DEL or DEL orientations as BNDs. Only one sided inversions and interchromosomal events

**Comment by crazyhottommy** [comment]
Great to know this!

Ming
