### ISSUE TITLE
Handle missing genotype (GT) information during VCF to BEDPE conversion

### ISSUE THREAD

**Issue by brunogrande** [hall-lab/svtools#130]
I'm trying to convert Manta VCF files to BEDPE files, which are more amenable for loading into R as a data frame. In doing so, I also ran into #129 and will comment there shortly. 

Separate from that issue is the fact that `svtools vcftobedpe` doesn't seem to handle the case where genotype (GT) information is missing from the input VCF file, as is the case with Manta VCF files. In the output BEDPE file, `GT` is added to the `FORMAT` column, but there aren't corresponding values in the subsequent sample columns. 

I'm not sure if genotype information is required by the VCF specification. If so, then it makes more sense to fill in something like `NA` in the sample columns. Otherwise, the GT key could be omitted from the `FORMAT` column. 

Below are two examples taken from the `FORMAT` and two sample columns from a Manta BEDPE file. Let me know if you need further clarification. 

```
GT:PR:SR	8,0:19,3	18,0:46,17
GT:PR	73,0	149,10
```

**Comment by ernfrid** [comment]
Thanks for the bug report @brunogrande. In this case, if we're going to add a `GT` key then the genotype should be `./.` I would have expected this to have happened for this case and I'll look into a fix.

**Comment by ernfrid** [comment]
This should be fixed in #139 and will be present in v0.3.0 of svtools.
