### ISSUE TITLE
Tandem duplication & deletion at same locus

### ISSUE THREAD

**Issue by fpbarthel** [hall-lab/svtools#156]
I found several cases where duplications and deletions are reported at the same loci. How can we interpret what's happening here?

Here are some examples (note that these are in three different samples)

    Chr1	Start1	End1	Chr2	Start2	End2	Name	Score	Strand1	Strand2	Type

    chr1	24786338	24786357	chr1	25577187	25577196	75	631.86	-	+	DUP
    chr1	24786346	24786351	chr1	25577180	25577198	76	416.08	+	-	DEL

    chr5	44984696	44984715	chr5	131658057	131658070	1915	1001.16	-	+	DUP
    chr5	44984701	44984715	chr5	131658062	131658080	1916	1220.27	+	-	DEL

    chr7	22433832	22433851	chr7	139648727	139648729	2785	1564.37	-	+	DUP
    chr7	22433849	22433852	chr7	139648726	139648745	2787	420.12	+	-	DEL

**Comment by cc2qe** [comment]
these are probably interspersed duplications, in which a small fragment is copied and inserted downstream. you may have to examine them individually in IGV to conclusively determine the nature of these events, but keep in mind that LUMPY is only looking at breakpoint orientation and doesn't consider read-depth support

**Comment by ernfrid** [comment]
another possibility may be gene jumping between the two copies of your chromosome. Similar to what we observed here: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3156695/ but on the same chromosome. Like Colby says, you're probably going to need to examine them in IGV or another program.

**Comment by fpbarthel** [comment]
Thanks both! Interesting read too.
