### ISSUE TITLE
SVtyper (0.0.4) randomly getting stuck

### ISSUE THREAD

**Issue by Phillip-a-richmond** [hall-lab/svtools#167]
Hello,
I'm running SVtyper on whole genome trio data for human, and for some reason the program just stalls out and stops outputting genotyped variants.  The variants it gets through processing worked fine, and then all of a sudden the process continues to run (tracking via htop) but there are no more genotyped variants being added to the output file. 

I've tracked via --debug, and nothing seems out of the ordinary regarding the variant it's processing.

Other things I've tried:
+ deleting the variants nearby the location it stalls on
+ Subsetting variants from a different chromosome

Neither of these have helped with the issue.  Has anyone else experienced this?  Unfortunately I don't think I'm allowed to share my input files, since they are clinically relevant.  Perhaps to diagnose my system if someone has a working example for me to try to genotype then that would help.

Thanks,
Phil

**Comment by ernfrid** [comment]
Hi Phil - It's not clear to me if you got an answer to this or not, but there's a test directory and script available that you could use to check if things are functioning correctly. For example, https://github.com/hall-lab/svtools/blob/master/svtools/bin/svtyper/test/run_svtyper.sh

You can use the test data in that directory (or similarly in recent versions of svtyper itself) and the command in that script to perform the test.

Let me know if it isn't abundantly obvious what to do from what I've linked you to.

**Comment by Phillip-a-richmond** [comment]
I'm trying a newer version (v0.1.0), and it doesn't recognize the -S argument.  Am I supposed to no longer supply the split read files, and only use the single complete BAM file instead?

**Comment by ernfrid** [comment]
Yes, I believe that's correct.

**Comment by ernfrid** [comment]
Thanks Phillip. I've posted an issue to SVTyper repository and hopefully that can be fixed before an official 0.1.0 release.

Glad to hear that the tool itself appears to be running. I'm going to close, but feel free to reopen if you are continuing to run into issues.
