### ISSUE TITLE
copynumber needs to handle -1 values

### ISSUE THREAD

**Issue by ernfrid** [hall-lab/svtools#173]
Turns out that cnvnator will output a value of -1 for copynumber under certain conditions. This is both invalid for later steps of the pipeline and indicative of a problem with the sample. Handle this condition more appropriately (throw an error).

**Comment by hirokomatsui** [comment]
Hi, I'm running copynumber and getting the error:
cnvnator produced a copynumber of -1 for variant 12 at coordinate 1
How can I avoid the error?

**Comment by ernfrid** [comment]
@hirokomatsui - We've only seen this happen when we've had corrupted files. Re-running cnvnator has fixed the issue. If that isn't the case for you, I'd recommend contacting the cnvnator authors here: https://github.com/abyzovlab/CNVnator/issues
