### ISSUE TITLE
svtools: error: unrecognized arguments: lsort_expected

### ISSUE THREAD

**Issue by 54tuifeimo** [hall-lab/svtools#223]
Hi!

I can run NA12878.vcf NA12891.vcf NA12892.vcf to Isort.vcf by subcomand of Isort. However, I can not run lmerge, even the  merge the file(lsort_expected) from lsort_expected svtools/tests/test_data/lsort.

svtools lmerge lsort_expected > Imerge.vcf
svtools: error: unrecognized arguments: lsort_expected

**Comment by ernfrid** [comment]
I think the issue is that lmerge doesn't accept positional arguments. I think either of these approaches should work:

1. Provide no arguments and have it operate on a stream.
   ```
   cat lsort_expected | svtools lmerge > lmerge.vcf
   ```

2. Use the -i option to specify an input file.
   ```
   svtools lmerge -i lsort_expected > lmerge.vcf
   ```

**Comment by ernfrid** [comment]
Great! You are right about the first method not working, I've made a note to add that functionality in the future.
