### ISSUE TITLE
Lsort ValueError: too many values to unpack

### ISSUE THREAD

**Issue by Gelblab** [hall-lab/svtools#236]
Hello Team, 

I was trying to run SVtools for merging calls across multiple whole genome samples. SVs were detected using speedseq pipeline. 

But when I tried to do lsort wih the VCF I got below error 

> Traceback (most recent call last):
>   File "/users/pateln54/.local/bin/svtools", line 11, in <module>
>     sys.exit(main())
>   File "/users/pateln54/.local/lib/python2.7/site-packages/svtools/cli.py", line 78, in main
>     sys.exit(args.entry_point(args))
>   File "/users/pateln54/.local/lib/python2.7/site-packages/svtools/lsort.py", line 118, in run_from_args
>     sorter.execute()
>   File "/users/pateln54/.local/lib/python2.7/site-packages/svtools/lsort.py", line 44, in execute
>     samples = l_bp.parse_vcf(input_stream, self.vcf_lines, self.vcf_headers, include_ref=self.include_ref)
>   File "/users/pateln54/.local/lib/python2.7/site-packages/svtools/l_bp.py", line 49, in parse_vcf
>     o_chr,o_pos = m.group(2).split(':')
> ValueError: too many values to unpack

Strange enough this error occurs with only some VCFs. 

I have used speedseq pipeline with -P -k -g  flags . CNVnator was run separately to create root files. 
and hence the "-d" flag was not used. Would that be reason for the error ? if so why would it occur to only certain VCFs ? 

Any suggestion on where to look into those VCFs for pin pointing the issue.

Best, 
Nick

**Comment by ernfrid** [comment]
The code that is causing an error only operates on `BND` type variants. It's hard to say exactly what is going wrong, but somehow it is unable to retrieve chromosome and position from the ALT field of a BND line.

I can think of 3 reasons why this might happen:

a) Some of the VCFs could be truncated. I'd check that the last line in affected VCFs looks valid.
b) The parsing code might not be handling an edge case chromosome name. Which reference sequence are you using? It may be that some of the chromosome names are not handled correctly.
c) There is some other error during creation of the VCF that results in an improperly formatted ALT field. It is difficult to determine if this is the case without identifying the precise line. If we can eliminate a) and b) then we can try to identify a specific problematic line for further troubleshooting.

**Comment by Gelblab** [comment]
Thanks For the prompt response.
I checked the VCF beforehand  to ensure they are not truncated. 

I am using  genome hg38 and  in the alternate field I had chromosomes   "HLA-DQB1*06:01:01" , which seems to cause the issue.  Removing calls with the chromosome solves the issue.  There are 18 such contig in new assembly, I am fine removing these calls but since these chromosome are part of hg38 assembly it's best if svtool can handle it or ignore it with warning.

These are chromosome ID's if it helps update the code 
HLA-DQB1*02:01:01
HLA-DQB1*02:02:01
HLA-DQB1*03:01:01:01
HLA-DQB1*03:01:01:02
HLA-DQB1*03:01:01:03
HLA-DQB1*03:02:01
HLA-DQB1*03:03:02:01
HLA-DQB1*03:03:02:02
HLA-DQB1*03:03:02:03
HLA-DQB1*03:05:01
HLA-DQB1*05:01:01:01
HLA-DQB1*05:01:01:02
HLA-DQB1*05:03:01:01
HLA-DQB1*05:03:01:02
HLA-DQB1*06:01:01
HLA-DQB1*06:02:01
HLA-DQB1*06:03:01
HLA-DQB1*06:09:01

Best, 
Nick

**Comment by Gelblab** [comment]
Sorry the star character did not appear in above comment , these are the chromosomes IDs
```
HLA-DQB1*02:01:01
HLA-DQB1*02:02:01
HLA-DQB1*03:01:01:01
HLA-DQB1*03:01:01:02
HLA-DQB1*03:01:01:03
HLA-DQB1*03:02:01
HLA-DQB1*03:03:02:01
HLA-DQB1*03:03:02:02
HLA-DQB1*03:03:02:03
HLA-DQB1*03:05:01
HLA-DQB1*05:01:01:01
HLA-DQB1*05:01:01:02
HLA-DQB1*05:03:01:01
HLA-DQB1*05:03:01:02
HLA-DQB1*06:01:01
HLA-DQB1*06:02:01
HLA-DQB1*06:03:01
HLA-DQB1*06:09:01
```

**Comment by ernfrid** [comment]
I think the current toolchain fails to handle the colons in these contig names correctly. It should be an easy fix and I'll aim to have it in the next release. Until that time, I'm going to leave this issue open.
