### ISSUE TITLE
the pre-result of CNVnator for svtools copynumber 

### ISSUE THREAD

**Issue by GangLiTarheel** [hall-lab/svtools#237]
Hi. I am trying to use SVtools copynumber to annotate a particular small region (~300kb) on Chr16. In the workflow, svtools assumed that we have run CNVnator and store the analysis at /temp/cnvnator-temp/NA12877.bam.hist.root. I wonder if you could share the script to create this root file.

CNVnator did provide a root file. I used it as input of svtools copynumber. It returns an "empty" vcf file, only with headers. My is that CNVnator could only call CNV for a whole chromosone. But I am not sure with that, I will double check with the author of CNVnator. Meanwhile, it would be great if you can provide the scripts in which you exactly create the root file with CNVnator or speedseq.

I have already install CNVnator and Speedseq, but I met an error with CNVnator:
_Can't open file with chromosome sequence.
No chromosome/contig information parsed.
Sequence length (0) is different from expectation (90338345) for 'chr16'.
Doing nothing!_

See my code:
_cnvnator -root $rootname.root -chrom $chrom  -tree $bam 2>err
cnvnator -root $rootname.root -chrom $chrom -his $bin_size -d /var/data/ 2>>err
bin_size was set to 10._

Thank you for your time and efforts.
Best,
Gang

**Comment by ernfrid** [comment]
If you use `speedseq sv` for your sv calling and preserve temporary files (`-k` then the cnvnator files should conform to that path.

However, you should be able to run independently. I believe the commands you are using look correct. I'd ensure that you have a file like chr16.fa containing the sequence of chr16 inside the directory you're passing to -d and I'd also use a larger bin size than 10. The smallest we use is 100. Based on your error message, I'd guess that the former issue is the problem.

**Comment by GangLiTarheel** [comment]
CNVnator ran smoothly and produced a ~4.2 Mb root file . But when I use that root file as the input of svtools copynumber, I meet an error: Can't find all necessary histograms for chromosome 'chr16' in file temp/cnvnator-temp/NWD100097.recab.bam.root. And the vcf produced only has headers. Any idea to solve this issue? 

Thank you for your time and efforts.
Gang

**Comment by ernfrid** [comment]
Hi @GangLiTarheel, in comparing what you've run versus what we typically run, I wonder if you may also need to run the partition command for cnvnator e.g. 

```
cnvnator -root $rootname.root -genome $genome -chrom chr16 
-d test -partition $bin_size
```

We also typically run calling as well, but I don't believe that should be needed.

The script we use is here: https://github.com/hall-lab/speedseq/blob/master/bin/cnvnator_wrapper.py

I have to offer my apologies as I thought I'd linked it in here in my last reply.

One last thought is that I would try matching the -w parameter in the svtools copynumber command to the binsize you use when running cnvnator.

**Comment by GangLiTarheel** [comment]
Hi  @ernfrid , thank you for replying me.
I ran the partition smoothly. Then I used the svtools copynumber. It returned a vcf file that only has header. The error is : 
>cnvnator produced a copynumber of -1 for variant 1 at coordinate 1

In addition, I have match the binsize at the beginning. My bin_size now is 5000. And the result of the cnvnator stat is：
>Making statistics for chr16 ...
Average RD per bin (1-22) is 0.770474 +- 0.100783 (before GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (before GC correction)
Correcting counts by GC-content for 'chr16' ...
Making statistics for chr16 after GC correction ...
Average RD per bin (1-22) is 0.547191 +- 0.00281957 (after GC correction)
Average RD per bin (X,Y)  is 0 +- 0 (after GC correction)

Any thoughts on that? 
I am running SVtools copynumber to annotate a particular small region (~300kb) on Chr16, in stead of the whole chromosome. Could this be the reason?

Best,
Gang

**Comment by GangLiTarheel** [comment]
After discussions with the author of CNVnator, I think I need to run it on a larger region, say ~5 Mb or the whole chromosome. In addition, he suggest me I could genotype the region, instead of call the copy number.

Thus I wonder, did the genotype information is richer than the copy number information? How does the three genotypes related to continuous copy number output of CNVnator? 

Did the svtools copynumber just run CNVnator to annotate the copy number? Did it use the genotype information before?

Best,
Gang

**Comment by ernfrid** [comment]
What svtools is doing behind the scenes is calling cnvnator genotype to genotype the region defined by the VCF entry. That returns a copynumber value for the region and that value is then added to the VCF in the CN tag.

The genotyping information from svtools is provided by svtyper. svtyper examines the insert sizes of paired-end reads and the locations of split-read alignments for support of candidate SVs to determine a genotype. The copynumber information is not used in the genotyping, but for variants where a number of conditions are true (sufficient size for accurate copynumber calling, unique enough breakpoints to allow for accurate genotyping, good fit of the variant to the genotyping models) we expect the genotype and copynumber to correlate.
