### ISSUE TITLE
Genotyping multiple samples with SVtyper

### ISSUE THREAD

**Issue by MehmetGoktay** [hall-lab/svtools#239]
Hi,

I want to do genotyping for couple of samples at the same time with svtyper. 

I wonder if svtyper deals with for the regions that has no coverage?

For example among 5 samples, we are interested in one region and 4 out of 5 accession shows the same sv but one does not. If this is the coverage issue, does svtyper gives missing genotype or some other signal that I can understand this is the coverage issue?

Best,
Mehmet

**Comment by ernfrid** [comment]
Yes, svtyper will report a missing genotype and a value of 0 for depth related measurements (DP, AO, AP, AS etc) if there is no coverage.

**Comment by MehmetGoktay** [comment]
Thank you very much for your answer.

To do that, do I need to call svs using 5 sample at the same time? 

Because I have called svs individualy per sample. And as far as understand I can not give more than one vcf file to svtyper. Do I need to merge them or should I call them again using 5 sample at the same time?

**Comment by ernfrid** [comment]
We typically merge them using the workflow described in the svtools tutorial, but you could also co-call if you prefer.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MehmetGoktay** [comment]
Thank you very much Dave.
