### ISSUE TITLE
KeyError: PE (lmerge step)

### ISSUE THREAD

**Issue by MehmetGoktay** [hall-lab/svtools#247]
Hi Dave,

I try to genotype bunch of samples with svtools lsort, svtools lmerge and svtools genotype.

I try to genotype around 1.2k samples with svtools. If I downsample this collection for example (100 accessions) I do have no problem. Eveything works properly but today I wanted to genotype everything together (1.2k samples). lsort worked but, I can not do lmerge step. 

I keep having this following error: 

 File "path/miniconda2/bin/svtools", line 6, in <module>
    sys.exit(svtools.cli.main())
  File "path/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/cli.py", line 78, in main
  File "path/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 632, in run_from_args
  File "path/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 597, in l_cluster_by_line
  File "path/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 539, in r_cluster
  File "path/miniconda2/lib/python2.7/site-packages/svtools-0.3.2-py2.7.egg/svtools/lmerge.py", line 422, in merge
KeyError: 'PE'

I m not so sure if there is any problematic sample which causes this or if it is an memory issue. Or something else.

If you can give me any idea to solve this problem, it would be awesome.

Best,
Mehmet

**Comment by ernfrid** [comment]
Hi Mehmet,

   The error indicates that lmerge was unable to find a PE tag in the INFO field of one of the files. 

I think it unlikely to be a memory issue, but we routinely run lmerge on sample sets of that size and request 13GB of RAM. That is generally more than sufficient so if you're requesting much less than that you could bump it up on the off chance it is a memory problem.

If all of your files were called with lumpy then I'd expect this field to exist and I would check that every line of your input has the same number of columns and that the number of lines for each sample seems reasonably consistent. In other words, I would first ensure that none of your input files show any signs of being truncated.

If neither of those suggestions appears to be a likely culprit then I'd attempt to specifically identify any lines where PE is not present in the INFO field to see if we can't find any hint in such lines (or lack thereof) about where to direct further effort.

Dave

**Comment by MehmetGoktay** [comment]
Hi Dave,

I have been investigating problem. I have not found any hint for this problem so far. I have repeated last two steps (running lumpy with -P again just to make sure and running svtyper per accession again). None of the runs returned any error. But most probably you are right at some point I had truncated files without any error. 

Today I have decided to run everything from the first step (mapping) just to make sure everything is as expected. I will update you whether it works or not. 

Thank you very much for your reply,
Mehmet

Mehmet

**Comment by ernfrid** [comment]
Hi Mehmet,
   Sorry to hear you've been unable to track this down thus far, that sounds frustrating. I'd be surprised if remapping the data solves this problem. If lumpy is able to complete successfully then we should be able to run the downstream tools. 

Did all lines of of you lsort output contain a PE entry in the INFO field? If so, then I'd think this is a parsing bug and nothing to do with truncated files at all.

Dave

**Comment by MehmetGoktay** [comment]
Hi Dave,

I have checked INFO column. (GT:SU:PE:SR:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB) 

Actually 3078 out of 2596704 lines does not contain PE tag.

But none of runs gave me error. (netiher svtyper nor lumpy with -P).So I m not sure what causes this missing tags. 

Do you have any suggestions?

Mehmet

**Comment by MehmetGoktay** [comment]
This is one of example where I have no PE tag.

1	15688282	2788_1	N	N[3:8902053[	446.74	.	SVTYPE=BND;STRANDS=+-:12;CIPOS=-10,9;CIEND=-10,9;CIPOS95=0,0;CIEND95=0,0;MATEID=2788_2;EVENT=2788;SU=12;SR=12;PRPOS=9.99968e-49,6.30937e-44,3.98095e-39,2.51181e-34,1.58484e-29,9.99968e-25,6.30937e-20,3.98095e-15,2.51181e-10,1.58484e-05,0.999968,1.58484e-05,2.51181e-10,3.98095e-15,6.30937e-20,9.99968e-25,1.58484e-29,2.51181e-34,3.98095e-39,6.30937e-44;PREND=9.99968e-49,6.30937e-44,3.98095e-39,2.51181e-34,1.58484e-29,9.99968e-25,6.30937e-20,3.98095e-15,2.51181e-10,1.58484e-05,0.999968,1.58484e-05,2.51181e-10,3.98095e-15,6.30937e-20,9.99968e-25,1.58484e-29,2.51181e-34,3.98095e-39,6.30937e-44;SNAME=sample	GT:SU:SR:GQ:SQ:GL:DP:RO:AO:QR:QA:RS:AS:ASC:RP:AP:AB	0/1:12:12:44:446.74:-46,-1,-6:32:13:18:13:18:0:0:0:13:18:0.58

**Comment by ernfrid** [comment]
Ok. That is very odd and I don't think this is a truncated file problem. What version of lumpy and svtyper are you using?

**Comment by ernfrid** [comment]
I'd also be curious to see how you're running lumpy (with what parameters etc).

**Comment by MehmetGoktay** [comment]
I used lumpyexpress (lumpy v0.2..13) and svtyper (v0.1.4)

And This is my pipline before using svtools for genotyping

#Run samblaster
samblaster -i $name.sam --excludeDups --addMateTags --maxSplitCount 2 --minNonOverlap 20 | samtools view --threads 50 -S -b - > $name.bam

# Extract the discordant paired-end alignments
samtools view --threads 50 -b -F 1294 $name.bam > $name.discordants.unsorted.bam

# Extract the split-read alignments
samtools view --threads 50 -h $name.bam   | extractSplitReads_BwaMem -i stdin | samtools view --threads 50 -Sb - > $name.splitters.unsorted.bam


# Sort both alignments
samtools sort --threads 50 $name.discordants.unsorted.bam -o $name.discordants
samtools sort --threads 50 $name.splitters.unsorted.bam -o $name.splitters



#Run Lumpy To Call SVs
lumpyexpress -P -B $name.bam -S $name.splitters -D $name.discordants -o $lumpyOutputDir$name.vcf

#Run SVtyper

samtools sort --threads 50 $name.bam -o $name.sorted.bam

samtools index $name.sorted.bam

svtyper -i $lumpyOutputDir$name.vcf -B $name.sorted.bam -l $jsonDirectory$name.bam.json > $name.svtyper.vcf

**Comment by MehmetGoktay** [comment]
I have analyzed 1.2 accessions. If I select like 100 and genotype them it works for some accessions. If I use for another 100 either it works or it doesn't. I don"t understand exactly what would be the reason.

I believe some of the samples that I use they causes this problem but I need to deeply investigate them ( by groping them into subsets to pinpoint which accessions actually causes this). But it will take me probably a week.

**Comment by MehmetGoktay** [comment]
Hi Dave,

Finally I have solved the problem. As you said it was "PE"  tag problem. I have iterated all vcf files which genotyped with svtyper 

for i in *.vcf
do
count=$(sed -n '50,$'p $i | awk '{print $9}' | grep -v ":PE:" | wc -l)
 if [ "$count" -ne "0" ]; then
               echo $i"		"$count	      
            fi
done

Using this script I got 2 accession ids which has "PE" tag problem. I removed them from my analysis then lmerge worked as expected. I will re-run everything from the beginning, if I still have those accessions with the problem, I will leave out them from my analysis permanently.

**Comment by ernfrid** [comment]
Hi Mehmet,
   That's good news. I'm puzzled what has happened with these two samples that you have lines without the PE tag. While our process is not identical to yours, we've run tens of thousands of samples through and I've not seen this issue before.

Please let me know if those two samples continue to have lines with missing PE tags after re-running.

Dave

**Comment by MehmetGoktay** [comment]
Hi Dave,

I will definitely let you know about the final outcome. Thank you very much for your help.

Mehmet

**Comment by MehmetGoktay** [comment]
Hi Dave,

I have finished genotyping step and the error still remains. But always same samples give error. I think it somehow related with those accessions. (quality, sequencing tech etc.) 

So I have removed them and I am good to go. 

Thank you very much for your help,
Mehmet

**Comment by ernfrid** [comment]
Thanks for the update Mehmet. I still don't understand what causes this, but I'm sure this will be helpful if anyone else encounters the issue.

**Comment by Prachi-Sardana** [comment]
Hi Dave, 
I encountered the same error. I have been trying to merge the VCfs using SVtools merge but I get the same error PRPOS tag error. 
svtools lsort worked fine, however, merging is creating a problem.
docker run -v /root/Project:/data halllab/svtools:v0.5.1 sh -c "zcat /data/sorted.vcf.gz | svtools lmerge -i /dev/stdin -f 20 | bgzip -c > /data/merged.vcf.gz"
Required tag PRPOS not found. Please ensure you've run lumpy withthe -P option to emit breakpoint probabilities.
