### ISSUE TITLE
Error: invalid INFO field, "POS"

### ISSUE THREAD

**Issue by ifiddes-10x** [hall-lab/svtools#251]
I am getting the above error when running the SVSCore pipeline. It seems to be caused by the `svtools vcftobedpe` step, but I don't understand why because the input file doesn't have a INFO field called POS anywhere. An example VCF entry from the VCF is

```chr1    649704  call_2326       G       <DEL>   70.0    PASS    END=649754;CIEND=0,0;CIPOS=0,0;SVTYPE=DEL;SVLEN=-50;PS=.;HAP_ALLELIC_FRAC=.;ALLELIC_FRAC=.;PAIRS=.;SPLIT=.;WildCov=.;MolTtl=.;MolTtlNoR=.;MolDel=.;MolDelNoR=.;MolWild=.;MolWildNoR=.;PVAL=.;BGSize=.;BGImparityPval=.;BGTtlRCnt=.;BGHP1RCnt=.;BGHP2RCnt=.;BGBaseCov=.;BGPhaseFrac=.;NRead=.;SOURCE=LOCAL_ASM   GT      1|1```

Any idea what would be causing this?

**Comment by ernfrid** [comment]
It appears this is a bug. The POS field is utilized during conversion and is supposed to be added if it is missing, but this appears to not be happening in your case.

As a temporary workaround, try adding this line to the header of your VCF:

`##INFO=<ID=POS,Number=1,Type=Integer,Description="Position of the variant described in this record">`

**Comment by ifiddes-10x** [comment]
Thanks! That seems to have worked. However, now I am getting a `Preprocessing failed` error:

```
bespin1 Thu Mar 22 14:59 SVScore $./svscore.pl -i HG2_LR22_combined.vcf.gz -d
Writing config file
Preparing preprocessing command
Preprocessing command:
awk '$0~"^#" {print $0; next } { print $0 | "sort -k1,1V -k2,2n" }' svscoretmp/HG2_LR22_combined1522165601.96677.vcf | bgzip -c > svscoretmp/HG2_LR22_combined1522165601.96677.sort.vcf.gz; vcfanno -ends conf.toml svscoretmp/HG2_LR22_combined1522165601.96677.sort.vcf.gz | perl /mnt/home/ian/SVScore/reorderheader.pl stdin svscoretmp/HG2_LR22_combined1522165601.96677.vcf | svtools vcftobedpe > svscoretmp/HG2_LR22_combined1522165601.96677.preprocess.bedpe

=============================================
vcfanno version 0.2.8 [built with go1.8]

see: https://github.com/brentp/vcfanno
=============================================
vcfanno.go:115: found 3 sources from 2 files
No SVTYPE parseable for chr1    649704  649704  chr1    649754  649754  call_2326       70.0    +       -       DEL     PASS    call_2326       G       <DEL>  .
        .       .       POS=649704      .       GT      1|1Preprocessing failed
```

However, that given record does have a SVTYPEL=DEL tag:

```
bespin1 Tue Mar 27 08:54 SVScore $zcat HG2_LR22_combined.vcf.gz | grep 649704
chr1	649704	call_2326	G	<DEL>	70	PASS	END=649754;CIEND=0,0;CIPOS=0,0;SVTYPE=DEL;SVLEN=-50;PS=.;HAP_ALLELIC_FRAC=.;ALLELIC_FRAC=.;PAIRS=.;SPLIT=.;WildCov=.;MolTtl=.;MolTtlNoR=.;MolDel=.;MolDelNoR=.;MolWild=.;MolWildNoR=.;PVAL=.;BGSize=.;BGImparityPval=.;BGTtlRCnt=.;BGHP1RCnt=.;BGHP2RCnt=.;BGBaseCov=.;BGPhaseFrac=.;NRead=.;SOURCE=LOCAL_ASM	GT	1|1
```

**Comment by ernfrid** [comment]
Does your VCF have a header line for SVTYPE? My guess is that it does not and this is also why the POS error occurred with the current codebase.

If not, I'd suggest adding it and reconverting to bedpe. Furthermore, I'd ensure that you have header lines for your existing INFO fields or I believe they'll be dropped during conversion to BEDPE and that may cause further downstream problems.

**Comment by ifiddes-10x** [comment]
Got it, thanks!
