### ISSUE TITLE
svtools genotype can be directly run with svtyper command

### ISSUE THREAD

**Issue by npatel22526** [hall-lab/svtools#259]
Hello, 

I was trying to run the latest version on SVtyper for svtools genotype step , is there a way to specify path to SVtyper  ? 

Also was wondering if below are comparable to each other 
`svtools genotype -l input.json -B input.cram`  Vs.  `svtyper -l input.json -B input.cram` 

Thanks, 
Nick

**Comment by ernfrid** [comment]
No, this isn't possible currently. However, `svtools genotype` is intended as a convenience wrapper for svtyper only. You can safely run svtyper directly and generally shouldn't expect there to be any problems in doing so.

**Comment by npatel22526** [comment]
Thank you for your input. Meanwhile I actually ran the command directly with svtper and it worked fine for that step and for all subsequent steps including reclassification. 

Best, 
Nick
