### ISSUE TITLE
Difficulty Using lsort (No SV calls outputted)

### ISSUE THREAD

**Issue by egoetz** [hall-lab/svtools#260]
Hello, I am attempting to use svtools to merge a number of VCF files I generated using Lumpy. In order to do so, I have tried calling lsort on several VCFs but when I went to examine the output, I found that only the VCF header and column labels had been generated. I found this quite odd as I was expecting either a complete file or an error message/non-zero exit code and I received neither. This is the command that I used to call sort:

`svtools lsort -f Documents/sample_of_6/filtered_vcfs/vcf_list.txt -t Documents/sample_of_6/filtered_vcfs/temp_dir -b 6 > ./Documents/sample_of_6/filtered_vcfs/l_merged.vcf
`

I already discussed this with Ryan Layer and he could not find anything wrong with my command. So he suggested I post here. Have any of you experienced a similar issue or have a theory as to what is happening? I very much would appreciate any help you can give me.

**Comment by ernfrid** [comment]
We've run into this occasionally. By default, `lsort` removes any samples that don't have variant genotypes. If your input files only contain homozygous references genotypes then no lines will make it through. If this is your issue you can work around it by using the `-r` argument.

If that's not your issue then I'm not certain what the problem might be. Are you able to provide an example?

**Comment by egoetz** [comment]
Thanks for such a prompt response! I did see some documentation on this,
however I did not truly understand it. What do you mean when you say
"homozygous
references genotypes"? Homozygous genotype I understand as a a segment of
DNA which has the same mutation in both alleles of a given gene. Please
correct me if I am wrong, as I am not a biologist and lack significant
training in that field.

I did not entirely understand where the reference portion came in either. I
am comparing VCF files that came from BAM files, which were all aligned to
the same reference genome if that helps to clarify anything.

I apologize if my questions are naive, but I very much appreciate the
help.

**Comment by ernfrid** [comment]
No apology needed, I'll rework my answer a bit then. 

You understand correctly for the most part. When I mention reference, I mean the reference sequence the sequencing reads were aligned to. When I said "homozygous reference genotype", I meant that the sample in question matches the reference on both alleles. In other words, the sample does NOT have the variant listed on that line of the VCF.

If you've run svtyper on your lumpy output files then some of the lines in the VCF may now indicate that the sample doesn't contain the variant lumpy predicted. However, if you're just taking the VCF produced by lumpy directly then the genotypes for all predicted variants are reported as "missing" and will be filtered out by lsort unless you use the `-r` option. Can you try running lsort with '-r' and see if that fixes your problem? (Please note that to proceed with lmerge after lsort , you'll need to have run lumpy with the -P option to put the full breakpoint probability distributions into the output)

**Comment by egoetz** [comment]
Oh, that makes perfect sense! Thank you so much for your explanation. adding the `-r` option did work. I can modify my scripts so that Lumpy utilizes the `-P` option. How do the probability curves from this option differ from the confidence intervals that Lumpy already adds to the info section?

**Comment by ernfrid** [comment]
The confidence intervals provide the positional range where there is likely to be a breakpoint and the probability curves provide more granular information about how likely a given base within that interval is the breakpoint location. `lmerge` uses the probability curves to refine variant location across overlapping predictions.

**Comment by egoetz** [comment]
Oh, thank you for the explanation-- it clarifies a lot. I will generate the VCFs using that option and hopefully will be able to proceed without problem.

**Comment by ernfrid** [comment]
Great! Good luck!
