### ISSUE TITLE
Combining sort and merge for aggregating vcd data

### ISSUE THREAD

**Issue by egoetz** [hall-lab/svtools#261]
After generating Lumpy VCFs with the `-P` option, I put a couple of them through lsort and lmerge. For example's sake, I used the following commands:
```
svtools lsort -r -f Documents/new_vcfs/vcf_list.txt > Documents/new_vcfs/output.vcf -b 2
```
```
svtools lmerge -i Documents/new_vcfs/output.vcf > Documents/new_vcfs/merged.vcf
```

I am confused however, as the output of the sort command had less SV calls than the output of lmerge. This is my main concern.

I am wanted to confirm that lmerge's output is correct. Take the following call (with each column being represented by bullet point):
- SL2.50ch02 
- 14406166 
- 15052 
- N 
- `<DEL> `
- 0 
- SVTYPE=DEL;STRANDS=+-:27;SVLEN=-645;CIPOS=-5,9;CIEND=-10,3;CIPOS95=-1,1;CIEND95=-1,1;IMPRECISE;SU=27;PE=24;SR=3;PRPOS=8.428907083734784e-17,3.351857691040371e-13,1.3327788386275796e-09,5.2994353000973725e-06,0.021065900839077806,0.8374643983889811,0.13255171319079714,0.008351123443519728,0.000526188413779997,3.31467852341437e-05,2.087848759050073e-06,1.3148809545185552e-07,8.279299143639335e-09,5.212300916887137e-10,3.281207877475404e-11;PREND=1.7986334688466868e-10,2.9081620912802324e-09,4.6981367532367596e-08,7.581109653060484e-07,1.2228726595900172e-05,7.842694768145708e-05,0.0005024992274977341,0.00321883013436882,0.020600154569674168,0.13181765214796257,0.8424159757300613,0.001351254102613529,2.1667619184186493e-06,3.4712678429713573e-09;ALG=PROD;SNAME=BGV013161:1955,BGV007023:2967;END=14406811

Are PRPOS's and PREND's format correct? I assume that there are four numbers indicating bounds for calls from both samples.

**Comment by ernfrid** [comment]
Yes, this is expected. `lmerge` expands BND variants into two separate lines and so the output file may have more lines than the input file. You'll see a note to this effect in the [tutorial](https://github.com/hall-lab/svtools/blob/master/Tutorial.md#use-svtools-lsort-to-combine-and-sort-variants-from-multiple-samples).

For PRPOS and PREND, you expect one value per base in the confidence interval (i.e. end - start + 1). Your output file appears to conform to that expectation.

**Comment by egoetz** [comment]
Thanks so much again. I did not see that note, so thank you for pointing it out to me.

**Comment by ernfrid** [comment]
You're quite welcome!
