### ISSUE TITLE
Does lmerge have a CI cutoff value?

### ISSUE THREAD

**Issue by egoetz** [hall-lab/svtools#262]
Hello again, I have a question regarding lmerge's methodology and would appreciate your insight. I have been reading through the files and wanted to make sure that my understanding was correct. In lmerge.py, the merge function is called by r_cluster. If the given break point has a larger minimum starting position than the current maximum ending position of the last SV, then merge is called on all SVs previously found to have overlapping position intervals in the same chromosome (lines 525-536). 

I understand this, but I am concerned-- does lmerge account for calls that are wildly imprecise (say a call with a start position with confidence intervals plus or minus 100 bp)? I have seen some similar calls in Lumpy VCFs when just considering the 95% confidence interval. To combat this problem, my team was using the 95% CI and made a imprecise cutoff value at +/- 10 bp. Given that lmerge is utilizing the entire CI, I would think that there is some way of accounting for this.

I will try to figure out the specifics of the merge function next, as I am trying to internalize the criteria used by lmerge. I am curious as to whether SV type is considered (as my team suggested it ought be) and if not, why? I also am going to try and find the section of code where probability curves are used and try to understand that. I just figured that I would ask questions as I go along so that I do not forget them.

Thanks again for all of the help.

**Comment by ryanlayer** [comment]
On Wed, Jun 27, 2018 at 3:20 PM egoetz <notifications@github.com> wrote:

> Hello again, I have a question regarding lmerge's methodology and would
> appreciate your insight. I have been reading through the files and wanted
> to make sure that my understanding was correct. In lmerge.py, the merge
> function is called by r_cluster. If the given break point has a larger
> minimum starting position than the current maximum ending position of the
> last SV, then merge is called on all SVs previously found to have
> overlapping position intervals in the same chromosome (lines 525-536).
>
> I understand this, but I am concerned-- does lmerge account for calls that
> are wildly imprecise (say a call with a start position with confidence
> intervals plus or minus 100 bp)? I have seen some similar calls in Lumpy
> VCFs when just considering the 95% confidence interval. To combat this
> problem, my team was using the 95% CI and made a imprecise cutoff value at
> +/- 10 bp. Given that lmerge is utilizing the entire CI, I would think that
> there is some way of accounting for this.
>
I am not sure I would call an SV with +- 100 bp wildly imprecises and I
don't think it is a problem per se. Large CIs are fairly common with SVs
that are supported only by paired-end reads, and in cases were an SV is
flanked by repeative regions you will not get split-reads. If you are doing
an analysis that needs single-base precision I would expect that even 10bp
could be too wide.

Each posistion in the CI has a probablity associated with it, and use the
product of all CIs to get the merged CI. If there is a mix of paired-end
(wide CI) and split-read (narrow CI) in a given cluster, then the product
with be narrow.

> I will try to figure out the specifics of the merge function next, as I am
> trying to internalize the criteria used by lmerge. I am curious as to
> whether SV type is considered (as my team suggested it ought be) and if
> not, why?
>
Type is considered as so far as we do not merge evidence for a DEL with
evidence for a DUP. Are you referring to a different type of consideration?


> I also am going to try and find the section of code where probability
> curves are used and try to understand that. I just figured that I would ask
> questions as I go along so that I do not forget them.
>
 The process used by lmgere is very similar to the process used by LUMPY,
so you may want to check out that paper as a companion to the code.
