### ISSUE TITLE
Where can I find the source codes if I install by conda?

### ISSUE THREAD

**Issue by zjgbz** [hall-lab/svtools#264]
Hi svtools users,

I installed the svtools on the virtual environment created by anaconda successfully. But I cannot find the source code of the svtools. I even tried to search the file name in my anaconda directory, but I found nothing. May I have your suggestion about this situation? Because I intend to adding lines of code about outputing the result during running svtools. Thank you in advance.

Best regards,
zjgbz

**Comment by ernfrid** [comment]
I haven't tried this specifically using anaconda, but I think what you probably want to try is outlined here: https://github.com/conda/conda-build/issues/1992#issuecomment-322588270.

Basically, with your environment activated, you should be able to clone the github repository for svtools, enter the top level of that repository, do `pip install -e .` and then make your changes.

**Comment by zjgbz** [comment]
@ernfrid Thank you very much! That really works. I can see the source code now.
