### ISSUE TITLE
Use whole chromosome to get CN

### ISSUE THREAD

**Issue by sususy** [hall-lab/svtools#265]
Hi,
When I use a small region"ch16:1-500000" of my bam files to run svtools, I could not get CN result. It is suggest that I should use the whole chr16. It worked. But maybe it is not necessary to use the whole chromosome. How about half chromosome or shorter? I wish there would be a timesaving length for CN result.

Thank you!

**Comment by sususy** [comment]
Also, in "speedseq sv" step, some samples need more 200GB, which is out of our slurm mem limit. Could you please tell me the maximum mem for each sample? 
Here is the code:
~/bin/speedseq sv \
	-B  ${name}.bam \
	-D  ${name}.discordants.bam \
	-S  ${name}.splitters.bam \
	-R ref.fa \
	-o ${name} \
	-w 100 \
	-g -d -P -T temp -k -v 
	
Thank you!

**Comment by sususy** [comment]
What if I only use a small part of reference like chr16:1-500000? Will that affect the result?

**Comment by ernfrid** [comment]
While it would be nice for cnv results to use less data, in practice, I don't think that cnvnator will work properly. Please see: https://github.com/hall-lab/svtools/issues/237 for a similar line of questioning and the outcome. I'm sure you could experiment for a given dataset, but it's unclear to me how much data you need to provide to get accurate results.
