### ISSUE TITLE
Svtyper  and svtools genotype

### ISSUE THREAD

**Issue by panzhaodong123** [hall-lab/svtools#268]
The difference between svtyper and svtools genotype,and which one is more credible?
The command:
svtyper：svtyper   -i  sv.vcf  -B sample.bam  -l sample.bam.json  > sv.gt.vcf
svtools：svtools  genotype -B bam -S split_bam  -i input_vcf -o output_vcf

**Comment by ernfrid** [comment]
They are the same. svtools includes svtyper in the codebase and uses svtools genotype as a convenient wrapper. 

The version of svtyper in svtools does tend to lag behind though and you may consider using svtyper directly to get the latest strategies.

**Comment by panzhaodong123** [comment]
When running svtyper,a Warning appeared,"Warning: --split_bam (-S) is deprecated";
And,the result of RS,AS,RP,AP is very different bewteen svtyper and svtools,that's why?

**Comment by ernfrid** [comment]
The version of svtyper included in the last release of svtools is quite old. The differences are due to improvements in svtyper that haven't been incorporated back into an svtools release (which is long overdue).
