### ISSUE TITLE
Not clear with the command to run svtools

### ISSUE THREAD

**Issue by amrita1983** [hall-lab/svtools#276]
Hello,

Trying to run svtools to convert Manta generated diploidSV.vcf file, into bedpe but cannot find the command to run it.
I am using this command:
svtools vcftobedpe diploidSV.vcf 

but its giving error.

**Comment by abelhj** [comment]
Try svtools vcftobedpe -i diploidSV.vcf

**Comment by amrita1983** [comment]
thanks it worked fine
