### ISSUE TITLE
Installation error with Pip because some packages rely on Python3

### ISSUE THREAD

**Issue by shangshanzhizhe** [hall-lab/svtools#300]
Hi, 
I used pip to install the SVtools in conda virtual env and encountered error, blew are the content of 
 the log:

`pip install svtools 2>&1 > error.log
Requirement already satisfied: svtools in /data/00/user/user103/.local/lib/python2.7/site-packages/svtools-0.5.1-py2.7.egg
Requirement already satisfied: svtyper==0.7.1 in /data/00/user/user103/miniconda2/lib/python2.7/site-packages (from svtools)
Requirement already satisfied: numpy in /data/00/user/user103/.local/lib/python2.7/site-packages (from svtools)
Requirement already satisfied: scipy in /data/00/user/user103/miniconda2/lib/python2.7/site-packages (from svtools)
Requirement already satisfied: statsmodels in /data/00/user/user103/miniconda2/lib/python2.7/site-packages/statsmodels-0.11.1-py2.7-linux-x86_64.egg (from svtools)`

AND final:
**statsmodels requires Python '>=3.5' but the running Python is 2.7.17**

I'd like to know how to fix this problem on installing the SVtools. Thank you!

Best,
Shangzhe

**Comment by shangshanzhizhe** [comment]
Hi,

Problem has just been solved. But I kept the issue, reminding other users that few dependency packages of SVtools only rely on Python3 right now. Such as statsmodels and cachetools. To solve this, you can install SVtools in a virtual enviornment. Before **pip install svtools**, you can  install the older version of the  statsmodels and cachetools, maybe
**statsmodels==0.90
cachetools==0.3.1**
This worked for me. Hope above could help.

Best,
Shangzhe

**Comment by skchronicles** [comment]
@shangshanzhizhe Do you mean `statsmodels==0.9.0`? I am not sure if that is a typo, but `statsmodels==0.90` does not exist. I ran into some issues while installing svtools and installing `statsmodels==0.9.0` prior to `svtools` fixed the issue.
