### ISSUE TITLE
Release a version of hall-lab-svtools in GitHub

### ISSUE THREAD

**Issue by brainstorm** [hall-lab/svtools#4]
Hello hall-lab!

I find your `vcftobedpe` script super useful for my purposes. I'm about to package svtools for bioconda:

https://github.com/bioconda/bioconda-recipes/tree/master/recipes

But in order to properly package it, I would need you to release a version of your package, preferably here on GitHub (ie: hall-lab-svtools-0.1.1.tar.gz that the package manager could download from instead of just the master branch):

https://help.github.com/articles/creating-releases/

Thanks in advance! Let me know if you need assistance releasing it.

**Comment by cc2qe** [comment]
Hi Roman,
SVTools is still in its pre-release stage, with several components still under internal testing at WashU. The code as well as format conventions are under active development, and thus we'd prefer not to circulate it widely until it is in a more stable condition. We'll tag a release when it is ready though

**Comment by brainstorm** [comment]
No worries, for now I'll just release tagging the revision ;)

https://github.com/brainstorm/bioconda-recipes/blob/master/recipes/hall-lab-svtools/meta.yaml#L6
