### ISSUE TITLE
Does not build, new locations look funny

### ISSUE THREAD

**Issue by ryanlayer** [hall-lab/svtools#43]
$ git pull
Already up-to-date.
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    long_description=open('README.txt').read()
IOError: [Errno 2] No such file or directory: 'README.txt'
$ touch README.txt
$ python setup.py build
running build
running build_scripts
error: file '**************************/svtools/bin/vcftobedpe' does not exist
$ find . -name vcftobedpe
./tests/test_data/vcftobedpe
$ grep vcftobedpe setup.py
    scripts=["bin/vcftobedpe","bin/varlookup","bin/svtools","bin/vcfsort",\
$ find . -name varlookup
./tests/test_data/varlookup
s$ find . -name svtools
./svtools
$ find . -name vcfsort
./svtools/bin/vcfsort
./tests/test_data/vcfsort

**Comment by ernfrid** [comment]
Sorry for the inconvenience. I think you were probably trying off of master and that setup.py is totally broken with the changes I've been making. I just merged in some new code to (hopefully) allow this to properly install. Can you pull down the changes and try again?

**Comment by ryanlayer** [comment]
Looks good.  Thanks.

**Comment by ernfrid** [comment]
Great. Thanks for letting me know. 

If you run into any difficulties just open an issue. I've moved things around a lot and haven't quite caught up all the docs yet.
