### ISSUE TITLE
svtools vcfpaste, passing in VCF names

### ISSUE THREAD

**Issue by ryanlayer** [hall-lab/svtools#44]
Previously I could use a wildcard "*vcf", but it no longer likes that:

```
$ svtools vcfpaste -f *ss

usage: svtools [-h] subcommand ...
svtools: error: unrecognized arguments:
svtools: error: unrecognized arguments: 1.vcf 2.vcf 3.vcf
```
So then I try to list them explicitly, same error:

```
$ svtools vcfpaste -f 1.vcf 2.vcf 3.vcf

usage: svtools [-h] subcommand ...
svtools: error: unrecognized arguments:
svtools: error: unrecognized arguments: 1.vcf 2.vcf 3.vcf
```

I noticed this bit in the usage page `Line-delimited list of VCF files to paste`

How do you do line-delimitation?

**Comment by cc2qe** [comment]
should work with each VCF filepath on a separate line. here's an example showing merging in batches of 200 samples, and finally into a VCF of the whole cohort
```bash
pwd
# /gscmnt/gc2719/halllab/users/cchiang/dev/vcf_paste_2016-01-04

wc -l /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt
# 4907 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt

mkdir -p split
split -a 2 -d -l 200 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt split/spl

# 2 hour 2 min
# commit (svtyper): 2b24a61503eab8274d659e70da357030614c9727
for FILE in `ls split`
do
    bomb -m 8 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f split/$FILE | gzip -c > $FILE.vcf.gz"
done

ls spl*.vcf.gz > batch_paste.txt

bomb -m 1 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f batch_paste.txt | bgzip -c > final.vcf.gz"
```

**Comment by ryanlayer** [comment]
Ah.  So -f expects a FILE of files, not a list of files (as the usage
states).

On Fri, Feb 12, 2016 at 11:15 AM, Colby Chiang <notifications@github.com>
wrote:

> should work with each VCF filepath on a separate line. here's an example
> showing merging in batches of 200 samples, and finally into a VCF of the
> whole cohort
>
> pwd# /gscmnt/gc2719/halllab/users/cchiang/dev/vcf_paste_2016-01-04
>
> wc -l /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt# 4907 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt
>
> mkdir -p split
> split -a 2 -d -l 200 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt split/spl
> # 2 hour 2 min# commit (svtyper): 2b24a61503eab8274d659e70da357030614c9727for FILE in `ls split`do
>     bomb -m 8 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f split/$FILE | gzip -c > $FILE.vcf.gz"done
>
> ls spl*.vcf.gz > batch_paste.txt
>
> bomb -m 1 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f batch_paste.txt | bgzip -c > final.vcf.gz"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hall-lab/svtools/issues/44#issuecomment-183436753>.
>



-- 
Ryan Layer

**Comment by ryanlayer** [comment]
This seems to work too:

svtools vcfpaste -f <(ls *vcf)

On Fri, Feb 12, 2016 at 11:39 AM, Ryan Layer <ryan.layer@gmail.com> wrote:

> Ah.  So -f expects a FILE of files, not a list of files (as the usage
> states).
>
> On Fri, Feb 12, 2016 at 11:15 AM, Colby Chiang <notifications@github.com>
> wrote:
>
>> should work with each VCF filepath on a separate line. here's an example
>> showing merging in batches of 200 samples, and finally into a VCF of the
>> whole cohort
>>
>> pwd# /gscmnt/gc2719/halllab/users/cchiang/dev/vcf_paste_2016-01-04
>>
>> wc -l /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt# 4907 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt
>>
>> mkdir -p split
>> split -a 2 -d -l 200 /gscmnt/gc2802/halllab/sv_aggregate/merge/re-GT/all.cn.txt split/spl
>> # 2 hour 2 min# commit (svtyper): 2b24a61503eab8274d659e70da357030614c9727for FILE in `ls split`do
>>     bomb -m 8 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f split/$FILE | gzip -c > $FILE.vcf.gz"done
>>
>> ls spl*.vcf.gz > batch_paste.txt
>>
>> bomb -m 1 "/gscmnt/gc2719/halllab/users/cchiang/src/svtyper/scripts/vcf_paste.py -q -f batch_paste.txt | bgzip -c > final.vcf.gz"
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hall-lab/svtools/issues/44#issuecomment-183436753>.
>>
>
>
>
> --
> Ryan Layer
>



-- 
Ryan Layer

**Comment by cc2qe** [comment]
i'm actually just going to reopen this so we remember to clarify the usage
