### ISSUE TITLE
A convention for BEDPE breakpoint positions

### ISSUE THREAD

**Issue by cc2qe** [hall-lab/svtools#49]
Opening a formal issue for discussions of the proper spec for representing exact breakpoints in BEDPE.

#### Potential Reporting Conventions
- Affected Bases (AFF)
  - pros
    - simple
  - cons
    - doesn't work for balanced translocations or BND variants
- Left of the breakpoint (LOB)
  - pros
    - symmetrical representation of ++/-- inversions and balanced rearrangements
  - cons
    - telomeric variants may have negative position
- Right of the breakpoint (ROB)
  - same as LOB except avoids negative positions (but may overhang chrom on right)
- Exact breakpoint (BPT)
  - pros
    - accurately represents breakpoints as space between two bases
    - symmetrical representation of ++/-- inversions and balanced rearrangements
  - cons
    - zero-length events may not be compatible with BEDTools intersections and clustering
- Last-aligned Base (LAB)
  - pros
    - simple description
  - cons
    - asymmetrical representation of ++/-- inversions and balanced rearrangements
    - size of the variant is `END - START + 1`

**Comment by cc2qe** [comment]
@ernfrid is it ok to link your Gist here?

**Comment by cc2qe** [comment]
reference https://github.com/hall-lab/svtools/issues/46

**Comment by ernfrid** [comment]
Definitely. Clearly need to go over all this code more. 

> On Feb 21, 2016, at 10:08 AM, Colby Chiang <notifications@github.com> wrote:
> 
> @ernfrid is it ok to link your Gist here?
> 
> —
> Reply to this email directly or view it on GitHub.
> 


____
This email message is a private communication. The information transmitted, including attachments, is intended only for the person or entity to which it is addressed and may contain confidential, privileged, and/or proprietary material. Any review, duplication, retransmission, distribution, or other use of, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is unauthorized by the sender and is prohibited. If you have received this message in error, please contact the sender immediately by return email and delete the original message from all computer systems. Thank you.

**Comment by cc2qe** [comment]
[Notes on SV representation](https://gist.github.com/ernfrid/e6af5c7a56758aaf3fbb)

**Comment by ernfrid** [comment]
Also, talked to Ira about this on Friday. He suggested we just mimic VCF, but we didn't have time to discuss in detail.

**Comment by lganel** [comment]
I think another pro for LOB is readability; for precise variants, the start/stop of the BEDPE interval are the bases flanking the breakpoint. For example, if an interval is `1 90 91`, the breakpoint is between the base at position 90 and the base at position 91.

**Comment by cc2qe** [comment]
^ that would actually be true of ROB, not LOB. but yeah i see your point

**Comment by cc2qe** [comment]
In support of BPT, [pairtopair](https://github.com/arq5x/bedtools2/blob/7f765bc81b27e5a311eed6172e59203735253960/src/pairToPair/pairToPair.cpp)  and [prune](https://github.com/hall-lab/svtools/blob/master/svtools/prune.py) would be the only scripts affected by this scheme. pairToBed would natively support a BPT scheme.

just checking through the pairtopair source, it looks like this modification would be trivially easy, since it would only require internally iterating the position by 1 base.

**Comment by ernfrid** [comment]
BEDPE file definition - http://bedtools.readthedocs.org/en/latest/content/general-usage.html

**Comment by ernfrid** [comment]
I believe we've agreed to the BPT record. #52 is open to address this.

**Comment by ernfrid** [comment]
#52 was merged. Closing this issue.
