### ISSUE TITLE
vcfToBedpe  strandness

### ISSUE THREAD

**Issue by crazyhottommy** [hall-lab/svtools#5]
Hi, Thanks for making this useful tool. I am using vcfToBedpe to convert vcf from lumpy.
The resulting bedpe files in column 9 and 10 have strandness info "+" "-"
what does exactly those strandness tell us?
for translocations (BND), I found there are 4 different combinations of the strandness.
for deletions, it is always` + -`
for inversions, it is always `+ +`
for duplications, it is always `- +`

Thanks very much!
Ming

**Comment by crazyhottommy** [comment]
let me make it more clear:

when I look at the vcf ouput for one sv, check the `strands=-+`.
BND as in the [vcf4.2](http://samtools.github.io/hts-specs/VCFv4.2.pdf) specification. 

```
14      38454918        5956_2  N       ]8:9174263]N    25.35   .       SVTYPE=BND;STRANDS=-+:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0
8       9174263 5956_1  N       N[14:38454918[  25.35   .       SVTYPE=BND;STRANDS=+-:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0;MATEID=....
```
when it is converted to bedpe:
```
8	9174253	9174271	14	38454908	38454926	my_sv	25.35  +   -  BND  ....
```
I noticed that the strands is  `+ -` for this particular example when converted to bedpe.

Now, compare it to the vcf4.2 specification:
```
REF ALT Meaning
s t[p[ piece extending to the right of p is joined after t
s t]p] reverse comp piece extending left of p is joined after t
s ]p]t piece extending to the left of p is joined before t
s [p[t reverse comp piece extending right of p is joined before t


The example in Figure 1 shows a 3-break operation involving 6 breakends. It exemplifies all possible orientations
of breakends in adjacencies. Notice how the ALT field expresses the orientation of the breakends.
#CHROM POS ID REF ALT QUAL FILTER INFO
2 321681 bnd W G G]17:198982] 6 PASS SVTYPE=BND
2 321682 bnd V T ]13:123456]T 6 PASS SVTYPE=BND
13 123456 bnd U C C[2:321682[ 6 PASS SVTYPE=BND
13 123457 bnd X A [17:198983[A 6 PASS SVTYPE=BND
17 198982 bnd Y A A]2:321681] 6 PASS SVTYPE=BND
17 198983 bnd Z C [13:123457[C 6 PASS SVTYPE=BND
```
and  look at the figure in the specification:

<img width="470" alt="screenshot 2015-12-02 14 28 10" src="https://cloud.githubusercontent.com/assets/4106146/11543213/05a0cdb0-9901-11e5-8467-d78b301a3e54.png">

My particular example will be similar to breakpoint `U` ( with strand +) and `V` (with strand -)

Do you think I am correct?

Thanks!
Ming

**Comment by cc2qe** [comment]
The strands field is an internal convention, and you should probably ignore it. It is a vestige of BEDPE, where deletions are always +-, dups are -+ and inversions are ++ or --.

note that the STRANDs field is __wrong__ for the secondary side of BND variants (anything with a SECONDARY info tag and a variant ID ending in _2). STRANDs reports the orientation of the primary breakend variant only. (This is why you should ignore STRANDs, and also why we'll probably remove it to avoid confusion in the future)

**Comment by cc2qe** [comment]
also, in general, those +/- orientations reflect the strands of inward facing reads

**Comment by crazyhottommy** [comment]
Thanks for your answer. That being said, how is it possible for one to figure out the translocation (fusion) direction of the breakpoints from a bedpe file converted from vcf? or I can only tell from the vcf file? I hate the `[` `]` notations..it is very hard for me to remember...


-------------A------|------B----------------  chr8
                 BND 5956_1
-------------C------------|-----D----------- chr14
                           BND 5956_2

How can I tell  it is A-C, A-D or B-C, B-D fusion?
Thanks!
Ming

**Comment by cc2qe** [comment]
yeah, the +- in the BEDPE file means that it connects A to D

++ would be A to C
-- would be B to D
-+ would be B to C

**Comment by crazyhottommy** [comment]
That's what I think. thanks for the confirmation!

Ming

**Comment by crazyhottommy** [comment]
So, `+` means the region at the 5' of the breakpoint and `-` means the region is at the 3' of  the breakpoint.

**Comment by cc2qe** [comment]
yup

**Comment by crazyhottommy** [comment]
I am sorry to open this again, but I am still a bit confused.
I know svtools is under active development, and even how to represent SVs in BEDPE format is still under discussion.

I am using `speedseq 0.1.0` to call structural variants.

I am particularly interested in translocations, I used `vcfTobedpe version: $Revision: 0.0.2 $` to convert the resulting vcf files to bedpe and there are 4 combinations of strandness of the SVs for `BND` type:

`+`  `-`
`+` `+` 
`-` `+`
`-` `-`

Now, I want to get the merged DNA sequences 50bp around the breakpoints after fusion.

---A-----|----|------B-----       chr8:100-200   `+`

-----C-----------|----|---D---  chr14:300-400   `-`

I understand from Colby's comments that it means fragment A fused with fragment D.
I need DNA sequences to be `chr8:100-150`   fused   `chr14:300-350`
It is straightforward in this case, I can just extract DNA sequences for these two fragments and stitch them together.

---A-----|----|------B-----       chr8:100-200   `-`

-----C-----------|----|---D---  chr14:300-400   `+`

this means B fused to C:
`chr8:150-200`     `chr14:350-400`
do I need to get the reverseComplement of `chr8:150-200` and reverseComplement of `chr14:350-400` and then stitch them together?

---A-----|----|------B-----       chr8:100-200   `+`

-----C-----------|----|---D---  chr14:300-400   `+`

this means A fused to C.
`chr8:100-150`  `chr14:350-400`
do I need just fuse `chr8:100-150` and  reverseComplement of `chr14:350-400`?

---A-----|----|------B-----       chr8:100-200   `-`

-----C-----------|----|---D---  chr14:300-400   `-`

B fused to D.
`chr8:150-200`  `chr14:300-350` 
do I need to just fuse reverseComplement of `chr8:150-200` and `chr14:300-350` ?


A function to get the resulting fused DNA sequences 50 bp around the breakpoints:

```r
getflank <- function(id,chr1,start1,end1,strand1,chr2,start2,end2,strand2,offset=50) {
  chr1 = sprintf("chr%s",chr1)
  chr2 = sprintf("chr%s",chr2)
 
  pos1 = ifelse(strand1=="+", end1, start1)
  pos2 = ifelse(strand2=="+", end2, start2)
 
  flank1 = getSeq(bsg,chr1,ifelse(strand1=='+', pos1-offset, pos1),ifelse(strand1=='+', pos1, pos1+offset))
  flank2 = getSeq(bsg,chr2,ifelse(strand1=='+', pos2-offset, pos2),ifelse(strand1=='+', pos2, pos2+offset))
   
  fused = sapply(1:length(id), function(i) {
    if(strand1[i] == '+' & strand2[i] == '-')
      fused = c(flank1[i],flank2[i])
   
    if(strand1[i] == '-' & strand2[i] == '+')
      fused = c(reverseComplement(flank1[i]), reverseComplement(flank2[i]))  ??
   
    if(strand1[i] == '+' & strand2[i] == '+')
      fused = c(flank1[i], reverseComplement(flank2[i]))  ??
   
    if(strand1[i] == '-' & strand2[i] == '-')
      fused = c(reverseComplement(flank1[i]),flank2[i]))  ??
   
    return(fused)
  })
 
  
  fused = sapply(fused, unlist)
 
  #str = paste(">",id,"\n",sapply(fused, toString),"\n",sep="")
  #cat(str)
  return(fused)
}

```
 
Thanks very much for your help!
Ming

**Comment by ernfrid** [comment]
Hi Ming — I'm still learning, but I believe you have the right ideas above in your prose (can't speak to the code) when you have exact breakpoints. I'm not clear on how to handle any uncertainty in the breakpoints and that may depend on your intent downstream.

I also don't think that you need to necessarily reverse complement both sides of the B -> C fusion, you could just fuse C (`chr14:350-400`) to B (`chr8:150-200`) and skip the reverse complementing.

**Comment by crazyhottommy** [comment]
Thanks for answering.

So, there is really no difference between `+` `-` and `-` `+` BNDs:

in bedpe format:

`chr8 100 200   chr14 300 400  + -`
is the same as 
 `chr14 300 400 chr8 100 200  - +`

e.g.

---A-----|----|------B-----       chr8:100-200   `+`

-----C-----------|----|---D---  chr14:300-400   `-`

A fused to D

can be represented as

-----C-----------|----|---D---  chr14:300-400   `-`

---A-----|----|------B-----       chr8:100-200   `+`

D fused to A

Am I right?

**Comment by cc2qe** [comment]
yes, that's correct. although keep in mind this only applies to BNDs. For variants on the same chromosome, +- is a deletion and -+ is a tandem duplication.

**Comment by crazyhottommy** [comment]
So, then how lumpy decides to represent a `-+` or `+-` translocation (BND) if it is essentially the same?

**Comment by cc2qe** [comment]
If you're asking about how LUMPY denotes reciprocal translocations, that information is shown in the STRANDS field of the VCF, which will have both +- and -+ entries for a reciprocal event.

If you're asking how LUMPY deals with the ambiguity you mentioned above, then it doesn't have to. That ambiguity is not present in VCF, only BEDPE

For issues on file formatting in general, I encourage you to consult the well-documented VCF spec. If there is confusion about what the BEDPE format is representing you can simply refer to the original VCF line.

**Comment by ernfrid** [comment]
Hi Ming, I'm going to close this, but do reopen a new issue if you have other questions.
