### ISSUE TITLE
Come up with packaging/release strategy

### ISSUE THREAD

**Issue by davidlmorton** [hall-lab/svtools#50]
Let's discuss.

The goal is to make it as simple as possible for users to install (without root).  The following two user stories seem realistic:

1. I want to use all the tools in the svtools suite in a pipeline.
2. I want to use just some of the tools (i.e. vcf-to-bedpe and bedpe-to-vcf).

Proposal:
  - Split repository up into multiple repositories, one for each tool (or logically related set of tools).
    - Benefits:
      - Allows for releasing tools separately (satisfying user story 2).
      - Isolates tools from one another so cross-dependencies cannot creep in.
      - Allows for more fine-grained testing and issue tracking.
      - Each tool (or tool set) could be implemented in language of choice.
    - Drawbacks:
      - Some developers feel more comfortable with a single repository
      - Automation for building conda and/or pypi packages would need to be created.
      - Some amount of boilerplate will exist in every repository.

**Comment by davidlmorton** [comment]
Numpy/Scipy dependencies drive some packaging/release decisions.  They are not compatible with the most common installation method (pip install <package_name>) [[background]](http://stackoverflow.com/questions/2213551/installing-scipy-with-pip).  I believe that conda is a good choice for packaging/releasing tools that depend on Numpy/Scipy.

```
$ cat <(pgrep 'numpy' * -l) <(pgrep 'scipy' * -l) | sort | uniq -c

      2 requirements.txt
      2 setup.py
      2 svtools/bin/svtyper/scripts/batchtyper
      2 svtools/bin/svtyper/scripts/sv_classifier.py
      2 svtools.egg-info/requires.txt
      1 svtools/lmerge.py
      2 svtools/reclass_combined.py
      2 svtools/#sv_classifier.py#
      2 svtools/sv_classifier.py
```

- svtyper is separate repo
- lmerge can be easily converted to use 'math' module from std library.
- #sv_classifier.py# appears to be duplicate of sv_classifier.py

So numpy/scipy are needed for:
    - reclass_combined.py
    - sv_classifier.py

**Comment by abelhj** [comment]
svtools/sv_classifier.py and svtools/reclass_combined.py are being
combined into one--I'm currently working on completing this.

I agree with using conda for installation of  numpy/scipy/pandas
dependencies--that was the only way I was able to install
successfully.

**Comment by ernfrid** [comment]
Currently this is working with pip (https://pypi.python.org/pypi/svtools/). While pip isn't the ideal case for installing numpy, pip installs of svtools are functional and pull in python library dependencies. In the case where numpy is already installed, I believe they work quite well.

I do agree with Dave that conda is a better option, but will seek to create the conda package after v0.2.0 and in a separate issue.
