### ISSUE TITLE
Converting to BEDPE is lossy

### ISSUE THREAD

**Issue by ernfrid** [hall-lab/svtools#54]
We lose the reference allele information and we also lose information in and around symbolic alleles. For example, `<DUP:TANDEM>` gets converted to simply `<DUP>`. If this is the correct behavior then symbolic allele lines need to be added/scrubbed from the headers appropriately.

**Comment by cc2qe** [comment]
my opinion is that BEDPE should not be lossy, and ref and alt alleles should be retained
