### ISSUE TITLE
##assembly lines are lost

### ISSUE THREAD

**Issue by ernfrid** [hall-lab/svtools#55]
Lines in the VCF header like ##assembly are getting scrubbed. Possibly additional lines would be scrubbed as well. Is this the proper behavior or does it need to be fixed? Seems improper to me.

**Comment by cc2qe** [comment]
improper behavior, should be fixed

___________________
Sent from mobile.

On Mar 9, 2016, at 22:31, Dave Larson <notifications@github.com> wrote:

Lines in the VCF header like ##assembly are getting scrubbed. Possibly
additional lines would be scrubbed as well. Is this the proper behavior or
does it need to be fixed? Seems improper to me.

—
Reply to this email directly or view it on GitHub
<https://github.com/hall-lab/svtools/issues/55>.
