### ISSUE TITLE
harmonize single character arguments for vcfpaste.py (other tools as well?)

### ISSUE THREAD

**Issue by jeldred** [hall-lab/svtools#80]
single character arguments to some tools have not been obvious to me (leading me to dig into the code to determine the intent of these arguments)
examples include
-m and -f to vcfpaste.py
I have found this to be most often confusing when the argument has an argument that is a file path or such.....I have specifically wondered if am I providing an input or output path for instance....
this suggests we may want to take a pass at the help text and names for these arguments
instead of proposing a specific harmonization strategy I recognize that changing this (or deciding not to change this might take some thought)
I create this issue to consider the issue.

**Comment by jeldred** [comment]
[svtools_argument_harmony.xlsx](https://github.com/hall-lab/svtools/files/245915/svtools_argument_harmony.xlsx)

**Comment by ernfrid** [comment]
@jeldred - Do you have recommended changes to go with this table?

**Comment by jeldred** [comment]
I recommend we add
-i, --input options to `copynumber` that has the same behavior as it's -v
-v, --vcf options to `genotype` that has the same behavior as it's -i
-i, --input options to `bedpetobed12` that has the same behavior as it's -b
-o, --output options to `bedpetobed12` that has the same behavior as -o in bedpetovcf and vcftobedpe
-i, --input options to `bedpetovcf` that has the same behavior as it's -b
-i, --input options to `prune` that has the same behavior as the positional arugment

**Comment by jeldred** [comment]
https://github.com/hall-lab/svtools/pull/128 and https://github.com/hall-lab/svtools/pull/131 are meant to address this issue

**Comment by jeldred** [comment]
PRs merged.
