### ISSUE TITLE
README.md needs to be updated

### ISSUE THREAD

**Issue by ernfrid** [hall-lab/svtools#96]
Should try to address issues raised in http://www.software.ac.uk/online-sustainability-evaluation as much as possible. Should provide current description, links to install and demo information, developer info, citation, mechanisms for user support.

**Comment by ernfrid** [comment]
Based on question in the online survey, trying to make sure we hit the following:
* Clear high-level overview including description of who should be trying to use it (type of user).
* Should have a unique name. Currently there is a logging framework (https://github.com/kayahr/svtools) and an R packaging tool with the same name.
* We need a deployed package where we don't have to build from source. Preferably conda and pip.
* Need our demo and potentially a quick start guide.
* Step by step install guide for both developers and non-developers
* Need to describe how to get help and what help can be provided.
* Troubleshooting guide
* Make sure version, web address, and licences for all third-party dependencies are listed and say whether the dependencies are mandatory or optional.
* Post build tests?
* Funding?
* Announcements or changelog?

**Comment by jeldred** [comment]
https://github.com/hall-lab/svtools/pull/120 addresses some but not all of this...

**Comment by jeldred** [comment]
closing with the release v0.2.0
